package com.prosegur.data.utils.exceptions

class DataIOException(message: String?, cause: Throwable?) : DataException(message, cause) {
}